### ISSUE TITLE
Hacktoberfest2021-Ekiti Participants Contributors Web App

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#1]
Building a web app that list the Hacktoberfest Ekiti Contributors 😊

So anyone with good with HTMl, CSS and JavaScript can make contributions here🤓

**Comment by larrick12** [comment]
Is there a link for the Api or I should write some logic to fetch information of those in Nigeria and contributing from ekiti ?.

**Comment by OSCA-Ado-Ekiti** [comment]
> How do I get the raw file or Api for the ekiti contributors
In the participants.json file sir

**Comment by oritselaye** [comment]
Anyone working on this?
