### ISSUE TITLE
Fix typo: On main web page

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#186]
![Screenshot 2022-10-25 at 5 45 01 PM](https://user-images.githubusercontent.com/85078495/197833928-5ee73330-cd0f-4217-abc0-cf4db68576b6.jpg)

there is a typo in this screenshot, please fix it, here is the path to the file: https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti/blob/main/public/index.html

**Comment by Rayo-git** [comment]
I have corrected it
