### ISSUE TITLE
Create the Mockup for Hacktoberfest Ekiti web app

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#2]
Anyone can pick this up and create a mockup of how the Hacktoberfest Ekiti web app should look like.

The main objectives is to have a little discussion about the hacktoberfest story at the top and also to list out the profiles of contributors.

**Comment by OSCA-Ado-Ekiti** [comment]
> OK let us see tomorrow

👀

**Comment by Victorayo** [comment]
Where will it be uploaded?

**Comment by OSCA-Ado-Ekiti** [comment]
> Where will it be uploaded?

- Fork this repo, 
- Create a new branch.
- Then click on Add file.

![repob](https://user-images.githubusercontent.com/85078495/137055016-43991b9c-e3f0-4f95-8b40-a644d806aa99.jpg)

- Now click on upload file.
- Then you can uppload the file.
- Finally file a pull request for it.
