### ISSUE TITLE
Create the lower middle section of the hactoberfest ekiti web page

### ISSUE THREAD

**Issue by Rayo-git** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#24]
![Screenshot_20211014-164140](https://user-images.githubusercontent.com/64208955/137352745-a4809528-7951-4ffe-aed1-8c4d44c5a7f3.jpg)

**Comment by larrick12** [comment]
@motunrayocyber how far have you gone on this ? 
Let me know if you kind of need any help.

**Comment by Anas-hameed** [comment]
Hello, I would like to work on this. Can you assign it to me?
