### ISSUE TITLE
Creating the Upper middle section of the Hacktoberfest Ekiti web 

### ISSUE THREAD

**Issue by samzzy-blink** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#25]
![4F6620CD-AB9C-46D5-84D4-4E894F9D0A75](https://user-images.githubusercontent.com/80962117/137353683-78ef1b1f-fe1a-4408-a712-9c5300e7266a.png)

**Comment by samzzy-blink** [comment]
I will be doing this part

**Comment by OSCA-Ado-Ekiti** [comment]
Which middle please, can you cut out the part you will be doing, so i can see

**Comment by samzzy-blink** [comment]
![0A22C2DC-93E4-44F8-9896-89FBDC1D27E3](https://user-images.githubusercontent.com/80962117/137354561-fc8abcc4-3463-4eb5-9877-bcebb6bb38eb.jpeg)

**Comment by samzzy-blink** [comment]
Work in progress

**Comment by OSCA-Ado-Ekiti** [comment]
Any update with this

**Comment by OSCA-Ado-Ekiti** [comment]
Any update yet on the text thats moving out of the cards? should we wait for the fix?
