### ISSUE TITLE
Create the Web Page Footer Section

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#3]
Create the footer section

You can create this with just HTML CSS and JavaScript 😌

**Comment by Haroonchik** [comment]
Здравствуйте я могу вам с этим помочь.

**Comment by samzzy-blink** [comment]
Morning , i can help out with it

**Comment by OSCA-Ado-Ekiti** [comment]
> Morning , i can help out with it



> Morning , i can help out with it

We are still waiting for the mockup guys, please hold on

**Comment by samzzy-blink** [comment]
Am working on the upper middle section already 
Don’t think I can do this part

**Comment by samzzy-blink** [comment]
But if am permitted to the two 
No problem then

**Comment by OSCA-Ado-Ekiti** [comment]
> I'll work on the Footer section. So please provide me some of your details (Contact Info, E-Mail and all) to Add on the Footer section. [https://in.pinterest.com/pin/769200811333235771/](url)

There is someone on the Footer sectionn already

**Comment by Elijah699** [comment]
@OSCA-Ado-Ekiti I need links for the footer section.

**Comment by OSCA-Ado-Ekiti** [comment]
Documentation: https://hacktoberfest-ekiti.web.app/docs

Contact: https://hacktoberfest-ekiti.web.app/contact

GitHub: https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti

Twitter: https://twitter.com/osca_ado_ekiti/status/1446376966303723546?t=oSuUuycQv5Yd7DdH32YlGw&s=19

**Comment by sachingagneja** [comment]
can i contribute in it?

**Comment by nerdyaltafofficial** [comment]
> Create the footer section
> 
> You can create this with just HTML CSS and JavaScript relieved

can i work on this

**Comment by priyanshu688** [comment]
@OSCA-Ado-Ekiti Can I work on this??

**Comment by prabhakar8050** [comment]
> > I'll work on the Footer section. So please provide me some of your details (Contact Info, E-Mail and all) to Add on the Footer section. [https://in.pinterest.com/pin/769200811333235771/](url)
> 
> There is someone on the Footer sectionn already

Okay Thanks
