### ISSUE TITLE
Edit title tags

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#68]
Rename the   <title>Hacktoberfest''21</title> of the Hacktoberfest Ekiti Web App.

Rename the title to "Hacktoberfest Ekiti 2021"

So all you will do is remove "Hacktoberfest''21" inside the <title></title> and put "Hacktoberfest Ekiti 2021".

So it ends up like this <title>Hacktoberfest Ekiti 2021</title>

**Comment by Victorayo** [comment]
What's the html link?

**Comment by Victorayo** [comment]
Couldn't locate the public folder yet. Can you help with a guide?
