### ISSUE TITLE
Adding the favicon to the site

### ISSUE THREAD

**Issue by OgunmisiM** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#85]
There is no favicon for the website ,is it assigned to anyone yet.

**Comment by OSCA-Ado-Ekiti** [comment]
the designer creating the logos is hadling this issue

**Comment by OgunmisiM** [comment]
Alright.

**Comment by OSCA-Ado-Ekiti** [comment]
You can generate the favicon now
