### ISSUE TITLE
What is Open Source?

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti#89]
Write the answers of "What is Open Source?" is here in [why-open-source.md](https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti/blob/main/public/docs/why-open-source.md)

**Comment by OgunmisiM** [comment]
I'll take this up.

**Comment by OgunmisiM** [comment]
Boss I fetched from upstream, I says I should pull request.

**Comment by OSCA-Ado-Ekiti** [comment]
Solved sir
